# Checks that the agent skill describes this release and that its links resolve.
#
#   cmake -DKARU_SOURCE_DIR=<repository> -P tests/agent_skill.cmake

if(NOT KARU_SOURCE_DIR)
    message(FATAL_ERROR "pass -DKARU_SOURCE_DIR=<repository>")
endif()

set(skill "${KARU_SOURCE_DIR}/.claude/skills/karu")
file(READ "${KARU_SOURCE_DIR}/VERSION" version)
string(STRIP "${version}" version)
file(READ "${skill}/SKILL.md" entrypoint)
string(FIND "${entrypoint}" "This skill describes **karu ${version}**" found)
if(found EQUAL -1)
    message(FATAL_ERROR "SKILL.md must say 'This skill describes **karu ${version}**'")
endif()

# Other agents read the same skill through a symlink. Where git checks symlinks out as
# plain files, as it does on Windows by default, the file holds the link target.
set(link "${KARU_SOURCE_DIR}/.agents/skills/karu")
set(link_target "../../.claude/skills/karu")
if(IS_SYMLINK "${link}" OR IS_DIRECTORY "${link}")
    file(REAL_PATH "${link}" resolved_link)
    file(REAL_PATH "${skill}" resolved_skill)
    if(NOT resolved_link STREQUAL resolved_skill)
        message(FATAL_ERROR ".agents/skills/karu resolves to ${resolved_link}, not ${resolved_skill}")
    endif()
elseif(EXISTS "${link}")
    file(READ "${link}" written_target)
    string(STRIP "${written_target}" written_target)
    if(NOT written_target STREQUAL link_target)
        message(FATAL_ERROR ".agents/skills/karu points to '${written_target}', not '${link_target}'")
    endif()
else()
    message(FATAL_ERROR ".agents/skills/karu is missing")
endif()

set(failures "")
file(GLOB references RELATIVE "${skill}" "${skill}/references/*.md")
foreach(reference IN LISTS references)
    string(FIND "${entrypoint}" "](${reference})" listed)
    if(listed EQUAL -1)
        list(APPEND failures "SKILL.md does not link ${reference}")
    endif()
endforeach()

file(GLOB_RECURSE documents RELATIVE "${skill}" "${skill}/*.md")
foreach(document IN LISTS documents)
    file(READ "${skill}/${document}" text)
    get_filename_component(directory "${skill}/${document}" DIRECTORY)
    string(REGEX MATCHALL "\\]\\([^)#: ]+\\.md(#[^)]*)?\\)" links "${text}")
    foreach(match IN LISTS links)
        string(REGEX REPLACE "^\\]\\(([^)#]+\\.md).*$" "\\1" relative "${match}")
        if(NOT EXISTS "${directory}/${relative}")
            list(APPEND failures "${document} links missing ${relative}")
        endif()
    endforeach()
endforeach()

if(failures)
    list(JOIN failures "\n  " report)
    message(FATAL_ERROR "agent skill problems:\n  ${report}")
endif()
message(STATUS "agent skill describes karu ${version} and its links resolve")
